name: Deploy to Linux Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Files
        run: |
          rm -rf /var/www/type-exp/*
          cp -r . /var/www/type-exp/
          cd /var/www/type-exp
          npm install --production


      - name: Restart App with PM2
        run: |
          cd /var/www/type-exp/dist
          pm2 delete type-exp || true
          pm2 start server.js --name type-exp
          pm2 save



